# This file is generated by scripts/publish-homebrew-tap.sh. Do not edit.
class AgentSvgtools < Formula
  desc "Machine-first CLI scoring AI-authored SVGs against raster references"
  homepage "https://github.com/wyrd-company/agent-svgtools"
  version "0.1.0"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.1.0/agent-svgtools-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "ac797109e12fbdb6bb3a4929bccddd0f932ee4d422c362e31cdaae75fc6cf797"
    end
    on_intel do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.1.0/agent-svgtools-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "d3ff3a315acc198b5f9681e7bc3d3713b08321f16323ddc2e2a3544bf899cdc9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.1.0/agent-svgtools-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "5dafe0b074794c2baa9ae8e51ed45f82409e874d09d4803bb11768ba15c1e26c"
    end
    on_intel do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.1.0/agent-svgtools-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6f80c8d582129c903b09c2effd9130a5105b38f17dd100eeab230a4ee0aeb1e3"
    end
  end

  def install
    bin.install "agent-svgtools"
  end

  test do
    assert_match "agent-svgtools", shell_output("#{bin}/agent-svgtools --version")
  end
end
