# This file is generated by scripts/publish-homebrew-tap.sh. Do not edit.
class AgentSvgtools < Formula
  desc "Machine-first CLI scoring AI-authored SVGs against raster references"
  homepage "https://github.com/wyrd-company/agent-svgtools"
  version "0.2.1"
  license "MIT OR Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.2.1/agent-svgtools-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "48d3917e668d0178b249fe199f1d1890dce2706eed2963379aaa866ec6bfa682"
    end
    on_intel do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.2.1/agent-svgtools-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "1251872f3a3a5762729968c8678558d400cea8e0b27c839e38b4ea27d7d780e7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.2.1/agent-svgtools-0.2.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "db55568071d1f0877e6065c159059e616435f6875d19692395f41a4398673482"
    end
    on_intel do
      url "https://github.com/wyrd-company/agent-svgtools/releases/download/0.2.1/agent-svgtools-0.2.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2b68ad306f7a8a3112f0248197a6ef4222383812ae378a309afcc26203a8c935"
    end
  end

  def install
    bin.install "agent-svgtools"
  end

  test do
    assert_match "agent-svgtools", shell_output("#{bin}/agent-svgtools --version")
  end
end
