# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpr < Formula
  desc "Review local git worktree branches as lightweight PRs"
  homepage "https://github.com/wyrd-company/gitpr"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.1/gitpr_0.3.1_darwin_x86_64.tar.gz"
      sha256 "abf2881d09765d44662715033d858edd5fed5b60108984a8ed30df7b4fc266cc"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.1/gitpr_0.3.1_darwin_arm64.tar.gz"
      sha256 "351212d63c84593468397861db0b75adec87935cb2544f8ae90845834149a415"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.1/gitpr_0.3.1_linux_x86_64.tar.gz"
      sha256 "802a5c15d4900f4dbb4f5d9dcc7862c71d907e82a8cbda7b6b87409c1d1ea136"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.1/gitpr_0.3.1_linux_arm64.tar.gz"
      sha256 "19fc3ecf6b83c50c81f2ee9130e6016fc4ca64de9ed9f631a34d0b237eaf869e"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  test do
    system "#{bin}/gitpr", "--version"
  end
end
