# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpr < Formula
  desc "Review local git worktree branches as lightweight PRs"
  homepage "https://github.com/wyrd-company/gitpr"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.2.0/gitpr_0.2.0_darwin_x86_64.tar.gz"
      sha256 "0c3076fb573c2e8a7cdaadb48084f293e5a1de005fd89cd41b19826f0f1007c3"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.2.0/gitpr_0.2.0_darwin_arm64.tar.gz"
      sha256 "58d9cdfe373f881c051701dfc826071e9d873d8dff237bf0e7e8ab51df191c37"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.2.0/gitpr_0.2.0_linux_x86_64.tar.gz"
      sha256 "645494b5373111e8b588cce21943a25f8ae245699faa5567657363addf329e77"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.2.0/gitpr_0.2.0_linux_arm64.tar.gz"
      sha256 "2d65bd0b330d447ad5150eb94716e39c25590c49f22775e7fc1f76b6a9b5955e"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  test do
    system "#{bin}/gitpr", "--version"
  end
end
