# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitpr < Formula
  desc "Review local git worktree branches as lightweight PRs"
  homepage "https://github.com/wyrd-company/gitpr"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.0/gitpr_0.3.0_darwin_x86_64.tar.gz"
      sha256 "a7b724502eb8e2d1eea6e886a94bc79273362949a5465fe6ee482117fbec9de7"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.0/gitpr_0.3.0_darwin_arm64.tar.gz"
      sha256 "cc61ebf80587cf8e41bae450f96a6c425e58c603e25a220a327a35b222a918f3"

      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.0/gitpr_0.3.0_linux_x86_64.tar.gz"
      sha256 "1a6f907e5aa7f07fef207f6c0005165e7609b05705624e4b17e335405a9eccfd"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyrd-company/gitpr/releases/download/0.3.0/gitpr_0.3.0_linux_arm64.tar.gz"
      sha256 "c2d96ca7e34c7b452ab23b48d969f5716515d773072669e5d619f01c9b72bc43"
      define_method(:install) do
        bin.install "gitpr"
      end
    end
  end

  test do
    system "#{bin}/gitpr", "--version"
  end
end
