# This file is generated by scripts/publish-homebrew-tap.sh. Do not edit.
class Lore < Formula
  desc "Project-scoped knowledge portal command-line client"
  homepage "https://github.com/wyrd-company/lore"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.1/lore-0.1.1-darwin-arm64.tar.gz"
      sha256 "8abd3f64647a9b2c3235fd2ac27e8cfca3565576086d838037bcbea61a8333c6"
    end
    on_intel do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.1/lore-0.1.1-darwin-amd64.tar.gz"
      sha256 "ca8a4ea43ea98b436979ee52aa78996f26ed03d57e4db3553bda43e4afa4e16f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.1/lore-0.1.1-linux-arm64.tar.gz"
      sha256 "79ecbe73fb6e96608a429fdb77509bfb47ea60155278f3fe7aaec052c1113eb1"
    end
    on_intel do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.1/lore-0.1.1-linux-amd64.tar.gz"
      sha256 "1d3c479e6a3355bcaa08b87563285ca8195bbda1d5084e6343e2f06fd5d3a991"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore #{version}", shell_output("#{bin}/lore --version")
  end
end
