# This file is generated by scripts/publish-homebrew-tap.sh. Do not edit.
class Lore < Formula
  desc "Project-scoped knowledge portal command-line client"
  homepage "https://github.com/wyrd-company/lore"
  version "0.1.7"

  on_macos do
    on_arm do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.7/lore-0.1.7-darwin-arm64.tar.gz"
      sha256 "b0e0369a42507b25e04040141a190af69316cbad6b7bdbf91cd5b983536dbf3d"
    end
    on_intel do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.7/lore-0.1.7-darwin-amd64.tar.gz"
      sha256 "cbf180f5c04ccb325a6fe85a677a8c3603e88e870a9a11743941925f6af76a44"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.7/lore-0.1.7-linux-arm64.tar.gz"
      sha256 "d4ea17fb8744e048d604c0e53aaab233f0abf97bce26ff5a67af231c2b83b2b5"
    end
    on_intel do
      url "https://github.com/wyrd-company/lore/releases/download/0.1.7/lore-0.1.7-linux-amd64.tar.gz"
      sha256 "407fb46e9d5694d6c228e99c892e580a7dc4cde4f1ce34e9dca63638009285b8"
    end
  end

  def install
    bin.install "lore"
  end

  test do
    assert_match "lore #{version}", shell_output("#{bin}/lore --version")
  end
end
